#!/usr/bin/env ruby
#
# jbmgen, a tool for generating the lib.jbm file for the Archos GMini
# Copyright (C) 2004 Simon Howard
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


require "JBMFile.rb"

def traverse_files(root_path)
    Dir.foreach(root_path) do |filename|
        next if filename == '.' || filename == '..'
        filename = "#{root_path}/#{filename}"
        if File.directory?(filename)
            traverse_files(filename) do |filename|
                yield filename
            end
        else
            yield filename
        end
    end
end

def find_archos
    mount_output = `mount`

    mount_output.each_line do |s|
        begin
            if s =~ /on (\S+)/
                path = $1

                if path =~ /^\// && File.exists?("#{path}/lib.jbm")
                    return path
                end
            end
        rescue
        end
    end

    nil
end

archos_path = find_archos

if archos_path == nil
    raise "Archos GMini not found!"
else
    puts "Archos GMini found at #{archos_path}"
end

file = JBMFile.new

traverse_files(archos_path) do |mp3|
    base_filename = mp3[archos_path.length+1, mp3.length]
    begin
        file.add_file(mp3, base_filename)
        puts base_filename
    rescue
    end
end

file.write_to 'lib.jbm'


