#!/usr/bin/env ruby
#
# jbmgen, a tool for generating the lib.jbm file for the Archos GMini
# Copyright (C) 2004 Simon Howard
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


require "JBMFile.rb"

def traverse_files(root_path)
    Dir.foreach(root_path) do |filename|
        next if filename == '.' || filename == '..'
        filename = "#{root_path}/#{filename}"
        if File.directory?(filename)
            traverse_files(filename) do |filename|
                yield filename
            end
        else
            yield filename
        end
    end
end

def find_archos
    mount_output = `mount`

    mount_output.each_line do |s|
        begin
            if s =~ /on (\S+)/
                path = $1

                if path =~ /^\// && File.exists?("#{path}/lib.jbm")
                    return path
                end
            end
        rescue
        end
    end

    nil
end

def helppage
    puts <<HELP_END

#{$0} : Generate lib.jbm files for use on Archos GMini 

Usage: #{$0} [ -p path ]

  -p path          Use path as the path to the mounted Archos device. Generate
                   lib.jbm in the root directory of the path.
		   By default, all mounts are searched for the existence of
		   an existing lib.jbm file as an indicator.
  -m media_path    Only catalogs files in media_path on the device.  For 
                   example, if your Archos is mounted at /mnt/sda1, and
		   you specify -m Music, only look in /mnt/sda1/Music for
		   mp3s.
  -o output_file   By default, a file 'lib.jbm' is generated on the root of
                   the archos path.  This allows you to override it and 
		   output to a different location.
  -q               Quiet operation

HELP_END
end

# parse command line options

archos_path = nil
quiet = false
media_path = nil
output_file = nil

i = 0

while i<ARGV.length

    arg = ARGV[i]

    case arg
        when '-p' then
	    i += 1
	    archos_path = ARGV[i]
	when '-h' then
	    helppage
	    exit
	when '-q' then
	    quiet = true
	when '-m' then
	    i += 1
	    media_path = ARGV[i]
	when '-o' then
	    i += 1
	    output_file = ARGV[i]
	else
	    puts "Invalid parameter '#{arg}'"
	    exit(-1)
    end

    i += 1
end

if archos_path != nil
    puts "Using Archos path #{archos_path}" if !quiet
else
    archos_path = find_archos

    if archos_path == nil
        raise "Archos GMini not found!  Please mount the Archos device or " +
    	      "use the -p command-line option."
    else
        puts "Archos GMini found at #{archos_path}" if !quiet
    end
end

if output_file == nil
    output_file = "#{archos_path}/lib.jbm"
end

file = JBMFile.new

if media_path == nil
    full_media_path = archos_path
else
    full_media_path = "#{archos_path}/#{media_path}"
end

traverse_files(full_media_path) do |mp3|
    base_filename = mp3[archos_path.length+1, mp3.length]
    begin
        file.add_file(mp3, base_filename)
        puts base_filename if !quiet
    rescue
    end
end

file.write_to output_file


